### ISSUE TITLE
Exception inheritance

### ISSUE THREAD

**Issue by Nyholm** [php-http/fig-standards#1]
The current draft is very similar to HTTPlug. The main difference is the exceptions. The proposed exceptions does not inherit each other. The exceptions we got is: 
- Something wrong with the request
- Something wrong with the transfer
- Bad response (4xx and 5xx)
- Other (base)

In my opinion they have nothing to do with each other and that is why I did not use inheritance. 
The reason why HTTPlug currently have inheritance is because the methods within those interfaces are similar. 

Also, HTTPlug do not have exception **interfaces**, we have classes. Inheritance between the classes makes sense because it make implementation easier. 

I want to know what you think, please refer me to any previous discussions if this has been mentioned before.

**Comment by Nyholm** [comment]
Issue updated.

**Comment by dbu** [comment]
how do other psr handle this? i would expect exception interfaces.

i find it convenient to say that network exception => response exception. when we have a request, it should be in the exception, when we have a response we for sure have a request as well and we should have both in the exception. 

that said, the only situation of having a response _exception_ in the future should be the error plugin (which basically makes the plugin client violate the contract of sendRequest if we say it may not throw an exception because of http status. i guess we should say **should** in that place)

**Comment by Nyholm** [comment]
> how do other psr handle this? i would expect exception interfaces.

Other PSRs do not do lots of exceptions... 

> i find it convenient to say that network exception => response exception. when we have a request, it should be in the exception, when we have a response we for sure have a request as well and we should have both in the exception.

Of course. That is still supported. But the exceptions do not inherit from each other. 

> that said, the only situation of having a response exception in the future should be the error plugin (which basically makes the plugin client violate the contract of sendRequest if we say it may not throw an exception because of http status. i guess we should say should in that place)

We say that by **default** we should not throw exception on http response status. One could still configure the client to throw that exception. IE, one does not need to use the ErrorPlugin.

**Comment by dbu** [comment]
> ```
> i find it convenient to say that network exception => response
> exception. when we have a request, it should be in the exception,
> when we have a response we for sure have a request as well and we
> should have both in the exception.
> ```
> 
> Of course. That is still supported. But the exceptions do not inherit
> from each other.

well, if its extending, i can use the same code to handle the request of
a RequestException as of a ResponseException

> We say that by _default_ we should not throw exception on http response
> status. One could still configure the client to throw that exception.
> IE, one does not need to use the ErrorPlugin.

that makes completely sense to me.

**Comment by Nyholm** [comment]
> well, if its extending, i can use the same code to handle the request of
> a RequestException as of a ResponseException

I agree, the **classes** could extend. Like we do in HTTPlug. 

But I do not think the **interfaces** should extend each other.

**Comment by sagikazarmark** [comment]
Honestly I am not sure that we should have interfaces for exceptions. Are there any real life use case for alternative implementations?

**Comment by sagikazarmark** [comment]
If someone need a custom exception, can just implement the Exception interface.

**Comment by Nyholm** [comment]
Are you suggesting to provide classes instead?

**Comment by dbu** [comment]
hm, difficult question if interface or implementations. the advantage of
interface is that e.g. guzzle could keep using its own exceptions and
start implement the interface, if the two are compatible. if we provide
impl, guzzle can't keep BC with their own extension hierarchy.

**Comment by dbu** [comment]
> But I do not think the _interfaces_ should extend each other.

i was thinking from the perspective of a client user. if the interfaces
don't extend, i can't typehint that i have "some exception that knows
about a request"

**Comment by Nyholm** [comment]
Two good points @dbu!

I do also think we should have interfaces for exceptions, even though implementations might be similar/identical. 

I like the idea of typehint for "some exception that knows about a request". What I don't like about interface inheritance is the following: 

``` php
try {
  // Send request
  throw new NetworkException($request);
} catch (RequestException $e) {
  echo "There is something wrong with your request, check your Request object.
}
```

Sure, if you write the code above you are doing things wrong. But without inheritance it is impossible to mess up. 

**Suggestion**: Should we add a `RequestAwareException` and `ResponseAwareException`?

**Comment by dbu** [comment]
and then RequestException and ResponseException would become pure marker
interfaces without additional methods? that feels actually quite right,
yes.rather on the verbose side, but correct. and people that don't care
about the Aware interfaces don't need to look at them at all.

what about making them just RequestAware and ResponseAware? the
interfaces could be handy for other things than exceptions. not sure if
that would be good design however.

**Comment by Nyholm** [comment]
I like that the aware interfaces could be used for other things. But it might be weird if we do not have anything else in mind than exceptions. 

Do you have any examples?

**Comment by dbu** [comment]
i don't have examples - don't think we will have any in the standard at least. in an API client, you might want to allow access to the raw response on a response object, to check headers or whatnot. there this might come in handy. but the api client library could also define a library specific interface. i am not 100% sure if we should make it general or not.

**Comment by sagikazarmark** [comment]
hm, we can provide a util package after all with exception implementations, just like psr-6.

About the Aware interfaces: not sure if I like the idea. From a domain perspective they mean nothing. They describe behaviour, but don't describe their place in the domain.

**Comment by Nyholm** [comment]
What is your opinion about a typehint for "some exception that knows about a request". Is it a good idea? Should we support that? Should we solve it with exception inheritance? Aware interfaces? Or something else?

I do not mind a util package, as long as the PSR interfaces are good and easy to use.

**Comment by sagikazarmark** [comment]
What's the point of such exception? Why would you want to catch exceptions this way (catch exceptions with request)? I would say, it should be done the other way around: catch relevant exceptions and process them accordingly. But even then, checking specific instances (RequestException, HttpException) would be better. That said, I am not so sure about inheritance anymore. An HttpException is not really a request exception. AFAIK we did it that way to expose the fact that it has a request and from a consumer point of view let them catch any exceptions where request is involved. I am not sure if I would do the same now, but I think it is still fundamentally different from saying "some exception which holds the request". Inheritance in our case is somewhat easier to use, while just using extra marker interfaces would cause a lot of confusion IMO.

**Comment by Nyholm** [comment]
The point of a `RequestAwareException` would be to catch it. It has no other purpose that convince. 

I do agree with you. One should use the domain exceptions instead of the "*Aware" exceptions with no meaning. Let's leave this for now. 

Aslo, This is not critique against our current implementation. We worked with **classes**. Our implementation will still be compatible with the current suggestion. 

---

> An HttpException is not really a request exception

So I hear that you are okey with the current implementation where exceptions **does not** inherit form each other.

**Comment by sagikazarmark** [comment]
> So I hear that you are okey with the current implementation where exceptions does not inherit form each other.

I am okay with it, although it won't give the flexibility that now we have that we are able to catch Request and HTTP exceptions in once.

**Comment by Nyholm** [comment]
No, it does not. 
Question is, do we need that? Have any of us ever use that anywhere?

**Comment by dbu** [comment]
my idea was different. having RequestAware / ResponseAware would allow this code:

``` php
try {
    ...
} catch (\Psr\Http\Client\Exception $e) {
    if ($e instanceof RequestAware) {
    ...
    }
}
```

so i think indeed calling it RequestAwareException would be wrong to do as catching that interface would be weird indeed. but the interface to know something has a request / response seems still useful. without, it would be something like `if ($e instanceof RequestException | $e instanceof NetworkException | $e instanceof HttpException)` which i find cumbersome.

**Comment by Nyholm** [comment]
As Mark said, a `RequestAware` interface has no place in the domain model. 

I think RequestAware / ResponseAware interfaces would be convenient. But I am equally fine without them. They may be more of value if there is 10+ exceptions (like in Guzzle's case)... 

For reference: PSR-3 includes a `LoggerAwareInterface` that lets you do `LoggerAwareInterface::setLogger`. This could used in dependency injection to add a logger service to objects implementing this interface. As far as I know, no other PSRs have a *Aware interface.

**Comment by dbu** [comment]
at least PSR-3 would make one precedence :-)
it sounds much like the same thing: not strictly necessary, but
potentially convenient and allows for simpler code.

**Comment by Nyholm** [comment]
@sagikazarmark ?

**Comment by sagikazarmark** [comment]
LoggerAwareInterface is a little bit different as it adds behaviour, not used as marker interface.

Having those interfaces adds a considerable amount of complexity (or at least some noise) to the standard IMO. I also think it's not that good if there is a design leak in the standard (allows badly designed code).

I never had the use case where I needed to do checks outside of the domain model (exception types vs. exception "behaviour).

**Comment by dbu** [comment]
we can propose the simple version and see if other people come up with
better arguments than me to re-add the complexity :-)

**Comment by Nyholm** [comment]
Good. So we are happy with #8?

**Comment by dbu** [comment]
not exactly happy, but i am also not sure that its wrong. so lets keep
it as is, without additional interfaces / inheritance and move on ;-)

**Comment by Nyholm** [comment]
Okey. Thanks.
