### ISSUE TITLE
Communicate immutability

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/fig-standards#12]
We should communicate that we use immutable objects and as such two objects of the same kind might have the same reference.

**Comment by Nyholm** [comment]
From #11:

> > It should be a note about the immutability somewhere. I think it should be in the interface and not the PSR description because the person that would need that note will probably not go to php-fig.com to read the PSR.
> > 
> > Or we could decide that a note about immutability is not needed at all..
> 
> Immutability comes from PSR-7. We should mention it where we state we use PSR-7.
