### ISSUE TITLE
Document the granularity of the exceptions

### ISSUE THREAD

**Issue by Nyholm** [php-http/fig-standards#14]
We do not have TimeOutException and HostNotFoundException. Why is that? 

I do not think we should introduce that, but I do think that should be documented in the meta document.

**Comment by sagikazarmark** [comment]
From the HTTP Client point of view these errors can be grouped under the Network related exception category. So even if we introduce such exceptions, they should be children of NetworkException.

However, from an error handling point of view: does it really make sense to distinguish between these error types?

I would say the exception message is perfectly fine as this is not an error which requires a domain handling logic. This is a fatal error, on a website you should show a nice unicorn saying sorry, in the console a big fat red sign. This usually indicates an infrastructural error, not an error in the application itself.

This is the reason I am against introducing such exceptions.

**Comment by Nyholm** [comment]
I agree. We should NOT introduce this. But we should document WHY we are not introducing these.  IE, write your arguments in the meta documentation.
