### ISSUE TITLE
Is it a requirement to implement NetworkException and RequestException?

### ISSUE THREAD

**Issue by Nyholm** [php-http/fig-standards#20]
Are we okey with an implementing library that does not implement `NetworkException` and `RequestException`? Could you really be a HTTP client without those exceptions?

On one hand, what kind of a poor client are you building if you do not support those exceptions...
But on the other hand, the only effect would be that the consuming library does not have a change to recover from the exception.

**Comment by sagikazarmark** [comment]
It depends: I think I mentioned somewhere that we should probably provide a util package which contains implementations for these exceptions. Honestly I am still not 100% convinced that it actually makes sense to have alternative implementations for exceptions, and this question is probably another proof of that (so as my proposed solution to have one package and reuse that).

But apart from that, if there is a common package and the client adheres the contract (throws these exceptions, no matter if anonymous class or not) then I would say it is not a requirement to have the actual implementations next to the client.

**Comment by Nyholm** [comment]
I do not mind of the exceptions are in a separate package or not. Im wondering, can you call a library a _HTTP Client_ if it **never** throws a `NetworkException`? Or if it **never** throws a `RequestException`?

**Comment by sagikazarmark** [comment]
I think so. It keeps the contract, but violates the domain.

Scenario:

Network timeout happens and it throws a NetworkException.

Network timeout happens and it just throws any exception which implements the parent.

In both cases the contract is kept, but in the latter case the domain is violated.

**Comment by Nyholm** [comment]
okey. Good. 

So I do NOT add something like: 

> An implementing library MUST implement both `NetworkException` and `RequestException`.

**Comment by sagikazarmark** [comment]
Well, I think it would make sense to mention the client at least MUST keep the contract, but it SHOULD NOT violate the domain.
