### ISSUE TITLE
Base Exception name

### ISSUE THREAD

**Issue by mindplay-dk** [php-http/fig-standards#27]
I'd like to propose you change the base exception name from `Exception` to `ClientException`.

Naming it `Exception` will lead either to confusing statements such as `catch (Exception $e)` and related bugs (such as forgetting the `use` statement) or perhaps more likely to unnecessary (and inconsistent) aliases in the majority of client code.

Defaulting to collisions and confusion/ambiguity with the core `Exception` class is not a good idea, and the base exception is clearly a class of general "client exceptions" any of which may be thrown by the "client", so the terminology seems to fit.

**Comment by Nyholm** [comment]
👍 
That sounds great. One could even name it `HttpClientException`

**Comment by mindplay-dk** [comment]
Works for me ;-)

**Comment by sagikazarmark** [comment]
Like the idea, but be aware with `HttpClientException`: we already have `HttpException` which would also be easy to confuse with.

**Comment by mindplay-dk** [comment]
@sagikazarmark good point, perhaps `ClientException` is less ambiguous.
