### ISSUE TITLE
Client configuration and HTTP exceptions

### ISSUE THREAD

**Issue by mindplay-dk** [php-http/fig-standards#28]
The spec and doc-blocks refers to "client configuration" without defining what is meant by that.

I summise it has to do with the following clause, which I regard as an inconsistency in the specification.

> all HTTP clients should follow the Liskov substitutions principle. This means that all clients should act the same when sending a request.

So far, so good - but then:

> *By default* a HTTP client should not follow redirect nor throw exceptions on HTTP responses with status 4xx or 5xx.

"By *default*" - so in other words, you *are* making an allowance here for breaking LSP, perhaps with the understanding that this be done via configuration?

And again in the doc-block of `HttpException`:

> This exception MUST NOT be thrown when using the client's default configuration.

It sounds like you're making an allowance for alternate configuration that may cause this exception to be thrown after all?

If that's what is implied, I strongly oppose such an allowance - clients will *not* be interchangible, and will violate LSP, if we can't know whether a client might throw an `HttpException` or not.

This will cause severe problems for any library class that depends on `HttpClientInterface`, since, as an implementor of such a class, I can't know whether I might need to handle this class of exceptions or not.

For example, any HTTP API service-wrapper *will* need to know whether it should handle exceptions or not, and, effectively, this means you can only assume you *have* to handle it, and, in fact, you will need to always make sure you handle *both* - for example:

```php
class IceCreamClient
{
    private $http;
    public function __construct(HttpClientInterface $http) {
        $this->http = $http;
    }
    public function getIceCream($flavor) {
        try {
            $response = $this->http->sendRequest(new Request("http://icecream.test/flavor/{$flavor}"));
        } catch (HttpException $e) {
            if ($e->getResponse()->getStatusCode() === 404) {
                // handle flavor not found....
            }
        }
        if ($response->getStatusCode() === 404) {
            // also handle flavor not found...
        }
        // handle success...
    }
}
```

In other words, all client code must handle two different possible means of HTTP error-code reporting.

This is particularly harmful to clients of REST HTTP APIs where the API overloads HTTP status-codes with domain meaning, such as is (unfortunately, IMO, but never the less) very widespread and popular practice.

I'm suspect you may be trying to "please everyone" by making these allowances (?) but in the end, this will more likely end up harming everyone.

I think you need to make a firm decision and stand by it - either:

1. Stipulate of client implementations that they *must* throw the `HttpException`, or
2. Stipulate that *no* client implementation may throw an `HttpException`

As argued, if the answer is (1) then this will lead to awkward implementations and inconsistent logic and flow in clients such as illustrated by the example above, as (sadly) many popular APIs overload the meaning of HTTP status codes such as 404 in particular.

I would therefore strongly prefer (2) in which `HttpException` is merely included as utility (interface or perhaps even class) that clients (such as the one in the example above) can elect to throw if *they* encounter HTTP status codes that *they* weren't expecting.

In other words, we (as an implementor of `HttpClientInterface`) can't know or assume what the meaning of any HTTP status code is - it is too often completely dependent on the HTTP API in question.

**Comment by Nyholm** [comment]
Thank you for this issue. I've been thinking a lot of this lately. It is weird that we say that http exceptions should not be thrown and then provide interfaces for http exceptions... I'll give you some clarifications and our basic idea: 

> "By default" - so in other words, you are making an allowance here for breaking LSP, perhaps with the understanding that this be done via configuration?

Correct. You (application users) can configure a client to throw exceptions. 

The idea is: 
Third party libraries should not care about exceptions. They should **always** assume that no exceptions is thrown. The libraries may use middlewares to make sure exceptions are thrown. That is why we have those interfaces. 

In php-http we have a `PluginClient` which is basically a "middleware client". We have one plugin/middleware that throws exceptions on 4xx and 5xx responses. Is our PluginClient a `HttpClient` according to the PSR if we say "Stipulate that no client implementation may throw an HttpException".

@sagikazarmark could you share your ideas.

**Comment by sagikazarmark** [comment]
This point has been brought up a thousand times which clearly indicates we haven't communicated the intent well.

The idea behind is that there are two common use cases for HTTP clients:

1. Wrapped in some kind of domain logic (eg. in form of a REST API client). In this case the client clearly shouldn't throw any exceptions and the wrapper layer should handle all responses.
2. "Raw" usage of the HTTP client: when you don't care about wrapping the HTTP layer, you just want to call a URL, maybe post some data, done. Although this is certainly not "the right way" to write code, his feature is commonly implemented in many clients, so clearly this is a use case (everyone done that before). Suitable for simple scripts or tests, etc. In this case interchangeability is less important.

Now, in this second case one might not really care about handling all "errors" just want to know if the request was success and know the reason why if not.

Since many existing clients implement this feature, we couldn't simply forbid that, but we could force that a zero-configured client MUST NOT throw such exceptions.

Clearly this is a huge leak in the API, and it would be much better if clients never throw exceptions....but it's not the case at the moment. This is the reason why we have an exception for those cases when there is already a response as well.

We thought about this a LOT, and so far this is the best that we could come up with.

In the end, we can't forbid clients to implement such feature and provide configuration for it. We might just remove any reference of this default configuration thing.

If we have to choose, I would rather choose not throwing exceptions, but there will always be clients which provide this feature and it's better that they do it by throwing an exception that's included in this standard.

**Comment by kelunik** [comment]
@sagikazarmark Then have two interfaces if there are two different use cases. Or rather one interface and a default implementation for the second use case, that just throws exceptions on errors and otherwise returns void.

**Comment by sagikazarmark** [comment]
Doesn't worth the effort and confusion IMO.

**Comment by kelunik** [comment]
Where's the confusion and effort?

**Comment by mindplay-dk** [comment]
I understand that there are two use-cases, as @sagikazarmark explained above, but the specific use-case is known only to the consuming code using it - if you're using constructor injection (like you should be) your client code has literally no way to know if the injected client is going to throw or not, and therefore must assume that it will throw.

Regarding LSP, as pointed out in the documentation, that's wrong.

Since only the consuming code can know the use-case (and assuming this PSR needs to cover the second use-case) basically your only option is to let the client somehow specify the expected behavior on a case-by-case basis, e.g. at call time - so either using a second argument to toggle the behavior, or having two distinct methods, one for each behavior.

Or provide a simple means of explicitly checking return codes, e.g. ship the package with a utility function to check and throw on demand, e.g. something like `HttpException::verify($response)`, which for the second use-case would mean:

```php
$response = $client->sendRequest($request);

HttpException::verify($response); // throws for 404/500 status
```

This lets consumer code opt in.

Defaulting to throwing exceptions vs permitting it, makes no difference to the consumer code - it *has* to assume an exception can be throw, and this is very harmful and clunky to work with, as argued and demonstrated above.

**Comment by dbu** [comment]
this reasoning does make sense to me. maybe we should really opt to write out all exception handling from the clients. php-http can provide an exception throwing wrapper or the error plugin as a non-psr thing. and if guzzle or some other client wants options to violate the psr, that is their freedom but we should not encourage it. at that point, the http exception tree would come from the php-http error plugin or guzzle.

**Comment by Nyholm** [comment]
It is great that this issue has brought up. We will say that the http client should NEVER throw exceptions. 

Thank you Rasmus
